name: WebServer
version: '${version}'
main: be.dailysurvival.webserver.WebServer
api-version: '1.20'
load: STARTUP
authors: [ Schreiffaut ]
description: Just a simple web server within a Minecraft Server.